name: Deploy Charts to environments

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (format: x-x-x)'
        required: true
        type: string
      environment:
        description: 'the environment to deploy to'
        required: true
        type: choice
        options:
          - rc-next
          - staging
          - prod
      target_repo:
        description: 'Optional: Specific repository to deploy (default: all repos)'
        required: false
        type: string

jobs:
  execute-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create script wrapper
        run: |
          cat > script-wrapper.sh << 'EOF'
          #!/bin/bash
          SCRIPT_PATH=$1
          shift
          chmod +x "$SCRIPT_PATH"
          "$SCRIPT_PATH" "$@"
          EOF
          chmod +x script-wrapper.sh
          # Make the directory executable
          find .github -type d -exec chmod +x {} \;
          # Make all scripts executable
          find .github -name "*.sh" -type f -exec chmod +x {} \;   

      - name: Run RC Next Workflow
        if: ${{ inputs.environment == 'rc-next' }}
        id: rc-next-workflow
        uses: ./.github/actions/rc-next-workflow
        with:
          release_version: ${{ inputs.release_version }}
          github_token: ${{ secrets.GHA_BOT_REPO_TOKEN }}
          github_actor: ${{ github.actor }}
          docker_hub_username: occasio
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          helm_username: ocamachine
          helm_registry: ghcr.io/occasio-technology-solutions
          target_repo: ${{ inputs.target_repo }}
